# Generated by Django 4.1.13 on 2026-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("score", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("percentage", models.IntegerField()),
                ("date_taken", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Quizzes",
            },
        ),
    ]
