# Generated by Django 4.1.13 on 2026-02-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz_app", "0002_quizresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("instructor", models.CharField(max_length=100)),
                ("thumbnail", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("modules", models.JSONField(default=list)),
            ],
        ),
    ]
